// mhdquad.js
import React from 'react';
import './mhdquad.css';

import frameTopImg from '../../Assets/mhd_frame_top.png';
import fabricationImg from '../../Assets/mhd_fabrication.png';
import mountedThrustersImg from '../../Assets/mhd_thrusters_mounted.png';
import resultsImg from '../../Assets/mhd_thruster_results.png';

function MHDQuadPopup({ title, onClose }) {
  return (
    <div className="project-modal-overlay" onClick={onClose}>
      <div className="project-popup-card-solid" onClick={(e) => e.stopPropagation()}>
        <span className="popup-close" onClick={onClose}>&times;</span>

        <div className="popup-scrollable-content">
          {/* INTRODUCTION */}
          <div className="popup-section">
            <h1 className="popup-title-solid">{title}</h1>
            <div className="popup-grid-solid">
              <div className="popup-left-solid">
                <p><span className="popup-label">Role:</span> Undergraduate Researcher, Magnetic Microsystems and Microrobotics Lab</p>
                <p><span className="popup-label">Date:</span> Winter 2025</p>
                <p><span className="popup-label">Advisor:</span> Professor Camilo Velez-Cuervo</p>
                <p><span className="popup-label">Skills:</span> SolidWorks, 3D Printing, Fabrication, Research Writing</p>
              </div>
              <div className="popup-right-solid">
                <img src={frameTopImg} alt="CAD Model of Frame" className="popup-image-solid" />
              </div>
            </div>
          </div>

          {/* GOAL SECTION */}
          <div className="popup-section">
            <h2 className="popup-subtitle">Goal</h2>
            <p>
              The project aimed to explore the feasibility of magnetohydrodynamic (MHD) propulsion for a miniaturized quadcopter.
              By leveraging saltwater and electric current, the design sought to enable micro-scale movement for future biomedical devices.
              Design constraints included size, simplicity, buoyancy, and minimal drag.
            </p>
          </div>

          {/* METHODS SECTION */}
          <div className="popup-section">
            <h2 className="popup-subtitle">Methods</h2>
            <p>
              A 3D-printable quadcopter frame was designed in SolidWorks with mountable ports for directional MHD thrusters. Thrusters were constructed from PCBs,
              permanent magnets, and precision-soldered header pins. Fabrication focused on ensuring polarity alignment and open bore channels.
            </p>
            <img src={fabricationImg} alt="Building the Thrusters" className="popup-image-solid" />
            <p>
              The thrusters were then mounted to the frame using epoxy and aligned directionally. Assembly was adjusted to accommodate wire routing,
              waterproofing, and connection stability.
            </p>
            <img src={mountedThrustersImg} alt="Mounted MHD Thrusters on Frame" className="popup-image-solid" />
          </div>

          {/* RESULTS SECTION */}
          <div className="popup-section">
            <h2 className="popup-subtitle">Results</h2>
            <p>
              During testing in a saltwater bath, visible saline jet streams were successfully generated by the quadcopter.
              However, full directional motion was limited due to cable stiffness and frame drag. Still, the results demonstrated
              proof of concept for MHD-generated thrust at small scales.
            </p>
            <img src={resultsImg} alt="Visible Jet Stream Results" className="popup-image-solid" />
            <p>
              The project laid the groundwork for future improvements in frame lightness, thrust-to-weight optimization,
              corrosion resistance, and onboard control.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default MHDQuadPopup;
